#define __in
#define __out
#define __inout
#define __in_opt
#define __out_opt
#define __inout_opt
#define __in_ecount(x)
#define __inout_ecount_part_opt(x,y)
#define __out_ecount_full_opt(x)
#define __inout_ecount_full(x)
#include <dxgi.h>
#include <d3d11.h>
#include <d3d12.h>
#include <nvapi.h>