name: zluda_dump Report
description: Share the zluda_dump logs to help us support your application.
title: "[Trace]: "
labels: ["zluda_dump logs"]
body:
  - type: markdown
    attributes:
      value: |
        TODO: We will post a tutorial for creating these logs. Add a link to it here.
  - type: textarea
    id: logs
    attributes:
      label: zluda_dump logs (tarball/zip file)
      description: |
        Please create a tarball (`.tar.gz`) or zip file (`.zip`) of your log directory and attach
        it here. You can drag and drop files directly into the comment box.
      placeholder: Attach file (e.g., drag and drop)
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Please describe the application you were running and provide clear, step-by-step
        instructions to run it.
      placeholder: |
        example:
          1. Download llm.c: git clone https://github.com/karpathy/llm.c.git
          2. Navigate to the directory: cd llm.c
          3. Download the model and train it:
            chmod u+x ./dev/download_starter_pack.sh
            ./dev/download_starter_pack.sh
            make train_gpt2fp32cu
            ./train_gpt2fp32cu
          4. Build and run the tests:
            make test_gpt2fp32cu
            ./test_gpt2fp32cu
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using? (e.g., distribution and version)
      placeholder:  "example: Ubuntu 22.04.5 LTS"
    validations:
      required: true
  - type: input
    id: gpu
    attributes:
      label: GPU
      description: What GPU are you using?
      placeholder:  "example: NVIDIA GeForce RTX 5080"
    validations:
      required: true
