[package]
name = "comgr"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>", "Joëlle van Essen <joelle@v-essen.nl>"]
edition = "2021"

[lib]

[dependencies]
amd_comgr-sys = { path = "../ext/amd_comgr-sys" }
libloading = "0.8"
