[package]
name = "zluda_preload"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = "0.4.3"
unwrap_or = "1.0.1"

[package.metadata.zluda]
linux_only = true
linux_symlinks = [
    "zluda_preload",
    "trace/zluda_preload",
    "trace_nvidia/zluda_preload",
]
