[package]
name = "zluda_fft"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "cufft"

[dependencies]
cuda_macros = { path = "../cuda_macros" }
cuda_types = { path = "../cuda_types" }
libloading = "0.8"

[target.'cfg(windows)'.dependencies]
zluda_windows = { path = "../zluda_windows" }

[target.'cfg(windows)'.build-dependencies]
embed-resource = "3.0"

[package.metadata.zluda]
linux_symlinks = [
    "libcufft.so.10",
    "libcufft.so.11",
    "libcufft.so.12",
]
windows_paths = ["cufft64_10.dll", "cufft64_11.dll", "cufft64_12.dll"]
