version: 2
build:
  os: ubuntu-lts-latest
  tools:
    rust: latest
  jobs:
    install:
      - cargo install mdbook mdbook-alerts --root .
    build:
      html:
        - PATH=$PATH:./bin mdbook build docs --dest-dir $READTHEDOCS_OUTPUT/html
